version: '3'

services:
  mysql:
    image: 'mysql:5.7'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_HOST=${DB_HOST:-127.0.0.1}
      - MYSQL_PORT=${DB_PORT:-3306}
      - MYSQL_DATABASE=${DB_DATABASE:-media_server}
      - MYSQL_USER=${DB_USERNAME:-media_server}
      - MYSQL_PASSWORD=${DB_PASSWORD:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-secret}
    ports:
      - 33306:3306

  node:
    build:
      context: ./
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    environment:
      - APP_ENV=${APP_ENV:-production}
    command: ./bin/run.sh

  nginx:
    image: 'nginx:latest'
    volumes:
      - ./:/var/www
      - ./var/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - mysql
      - node
